return {
  { "rcarriga/nvim-notify", enabled = false },
  -- { "rafamadriz/friendly-snippets", enabled = false },
  -- { "folke/trouble.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "nvim-mini/mini.indentscope", enabled = false },
  -- { "nvim-mini/mini.surround", enabled = true },
  { "kylechui/nvim-surround", enabled = false },
  { "nvim-mini/mini.pairs", enabled = false },
  -- { "echasnovski/mini.comment", enabled = false },
  -- { "Saghen/blink.cmp", enabled = false },
  { "ibhagwan/fzf-lua", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
}
